# Site settings
author: Laura Felce
title: Fresh Syntax Errors
header-img: img/home-bg.png
email: crepu83@yahoo.it
copyright_name: Laura Felce
description: > # this means to ignore newlines until "baseurl:"
  Coding experiences
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PrincessLaurora

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
